variable "app_name" {}
variable "app_services" {}
variable "account" {}
variable "region" {}
variable "service_config" {}
variable "ecs_task_execution_role_arn" {}
variable "vpc_id" {}
variable "private_subnets" {}
variable "public_subnets" {}
variable "public_alb_security_group" {}
variable "internal_alb_security_group" {}
variable "internal_alb_target_groups" {}
variable "public_alb_target_groups" {}
