context:
  region: apne2
account: 000000
region: us-west-1
name: queryfi
env: dev
app_services:
  - app
  - postgresql


#vpc
cidr: 10.0.0.0/16
azs:
  - us-west-1a
  - us-west-1b
private_subnets:
  - 10.0.1.0/24
  - 10.0.2.0/24
public_subnets:
  - 10.0.101.0/24
  - 10.0.102.0/24
enable_nat_gateway: true
enable_vpn_gateway: true

tags:
  project: env_vars_manager
  Terraform: "true"
  Environment: dev
  Owner: martin

ecs_launch_type: FARGATE
network_mode: awsvpc
ignore_changes_task_definition: true
propagate_tags: TASK_DEFINITION
desired_count: 1
task_memory: 512
task_cpu: 256

#container_definition
container_name: geodesic
container_image: cloudposse/geodesic
container_memory: 256
container_memory_reservation: 128
container_cpu: 256
container_essential: true
assign_public_ip: true
container_environment:
  - name: string_var
    value: I am a string
  - name: true_boolean_var
    value: true

container_port_mappings:
  - containerPort: 80
    hostPort: 80
    protocol: tcp
  - containerPort: 443
    hostPort: 443
    protocol: udp
force_new_deployment: true
redeploy_on_apply: true
