context:
  region: apne2

name: queryfi

#vpc
cidr: 10.0.0.0/16
azs:
  - us-west-1a
  - us-west-1b
private_subnets:
  - 10.0.1.0/24
  - 10.0.2.0/24
public_subnets:
  - 10.0.101.0/24
  - 10.0.102.0/24
enable_nat_gateway: true
enable_vpn_gateway: true

#ecr
ecr_name:
  - app
  - postgresql

tags:
  project: env_vars_manager
  Terraform: "true"
  Environment: dev
  Owner: martin