context:
  region: apne2
account: 000000
region: us-west-1
name: queryfi
env: dev
app_services:
  - app
  - postgresql


#vpc
cidr: 10.0.0.0/16
azs:
  - us-west-1a
  - us-west-1b
private_subnets:
  - 10.0.1.0/24
  - 10.0.2.0/24
public_subnets:
  - 10.0.101.0/24
  - 10.0.102.0/24
enable_nat_gateway: true
enable_vpn_gateway: true

tags:
  project: env_vars_manager
  Terraform: "true"
  Environment: dev
  Owner: martin

ecs_launch_type: FARGATE
network_mode: awsvpc
ignore_changes_task_definition: true
propagate_tags: TASK_DEFINITION
desired_count: 1
task_memory: 512
task_cpu: 256

#container_definition_app
container_app_name: geodesic
container_app_image: cloudposse/geodesic
container_app_command:
  - uvicorn
  - main:app
  - --host
  - 0.0.0.0
  - --port
  - 8000
  - --reload
container_app_memory: 256
container_app_memory_reservation: 128
container_app_cpu: 256
container_app_port_mappings: 8000
container_app_essential: true
container_app_environment:
  - name: POSTGRES_DB
    value: postgres
  - name: POSTGRES_USER
    value: admin
  - name: POSTGRES_PASSWORD
    value: admin
#container_definition_postgresql
container_postgresql_name: postgres
container_postgresql_image: postgres/15.2-alpine
container_postgresql_memory: 256
container_postgresql_memory_reservation: 128
container_postgresql_cpu: 256
container_postgresql_port_mappings: 5432
container_postgresql_essential: true
container_postgresql_environment:
  - name: string_var
    value: I am a string
  - name: true_boolean_var
    value: true


